### ISSUE TITLE
Translation of the Location Link between Asset and Location

### ISSUE THREAD

**Issue by SvenPeldszus** [georghinkel/ttc2017smartGrids#11]
Hello,

in line 6 of the task 1 listing is written that Location links of assets and the referenced Location node should be kept as a Location node in the view model.

We interpreted this in the way, that this link should be translated also for MeterAssets which is a subtype of Asset. Therefore, for every translated MeterAsset with a link to a Location also a reference to a corresponding Location in the view is created by our solution.

We just noticed that in the given reference solution this Locations are not translated. Did we interpret this wrong? E.g. in the sequence1 for the models 000.

Thank you,

Sven

**Comment by georghinkel** [comment]
Only the locations of MeterAssets have to be translated in the view.

**Comment by SvenPeldszus** [comment]
Yes, that is clear to me but the ModelJoin solution doesn't translate any Location linked directly linked to a to a MeterAsset, which is considered in the join, over a Location reference. While our solution does this for the mentioned example.

Are there translated Locations  expected for this example?

**Comment by georghinkel** [comment]
In that case you found a bug in the reference solution. Perhaps I was not sufficiently suspicious about the QVTo transformations generated by ModelJoin. I will take a closer look into this issue immediately.

But yes, for any MeterAsset for which there is a corresponding physical device in the cosem model, the referenced location should have a corresponding Location element in the resulting view.

**Comment by georghinkel** [comment]
So yes, there should actually be locations in the target model.

**Comment by SvenPeldszus** [comment]
Thank you very much for the quick response and clarification
