### ISSUE TITLE
Paths in change specifications

### ISSUE THREAD

**Issue by szarnyasg** [georghinkel/ttc2017smartGrids#2]
I have two remarks on change specifications:

1. Some, e.g. [CIM_DCIM-delta002.xmi](https://github.com/georghinkel/ttc2017smartGrids/blob/master/changes/changeSequence1/CIM_DCIM-delta002.xmi) contain absolute path, such as `file:///D:/Projekte/TTC%202017/Smart%20Grids/models/CIM_DCIM.xmi#_3801201SmartMeter/_3801201SmartMeter`.
2. The ones with relative paths use a mix of Windows-style and Unix-style path specification, e.g. [CIM_DCIM-delta001.xmi](https://github.com/georghinkel/ttc2017smartGrids/blob/master/changes/changeSequence1/CIM_DCIM-delta001.xmi) specifies `..\..\models/CIM_DCIM.xmi#_2800201SDL/`.

**Comment by georghinkel** [comment]
Yeah, the reason for that is that I recently created a new version of the generator that introduced relative paths. The generator will use those path separators that are standard on the platform that executed the generator, but I can change that to unix-style paths in all circumstances

**Comment by georghinkel** [comment]
Should be fixed with 163829177e317a15b3ade55d87f7922a118c36b3
