### ISSUE TITLE
"Changes" meta-model

### ISSUE THREAD

**Issue by dstrueber** [georghinkel/ttc2017smartGrids#6]
Hi! Is it possible to make the "changes" meta-model (http://nmf.codeplex.com/changes) available? Thanks!

**Comment by georghinkel** [comment]
Hi!

It already is: [https://github.com/georghinkel/ttc2017smartGrids/blob/master/metamodels/NMetaChanges.ecore](NMetaChanges.ecore)

However, I initially forgot to upload the change metamodel. You may have to pull the last commit.

Best,

Georg

**Comment by dstrueber** [comment]
Ah, I see. Thanks for the quick and helpful reply!
