### ISSUE TITLE
String attribute in Listing 1

### ISSUE THREAD

**Issue by dstrueber** [georghinkel/ttc2017smartGrids#7]
Hi,

Listing 1, Line 5 in the case description mentions an attribute called "Consumer.ControlAreaID:String", but there doesn't seem to be a class "Consumer" or an attribute "ControlAreaID" in the target meta-model. I did a full-text search on the complete repository for both, but did not find any matches. Is there a mistake?

**Comment by georghinkel** [comment]
Yes, that is a mistake. It should have been EnergyConsumer.ControlAreaID instead of Consumer.ControlAreaID. Unfortunately, the ModelJoin tooling does not throw an exception.

I will upload a new version that includes the missing attribute soon.

**Comment by dstrueber** [comment]
Thanks! But are you sure about the correct attribute name being "ControlAreaID"? There doesn't seem to be such an attribute in the EnergyConsumer class.

**Comment by georghinkel** [comment]
ModelJoin works by generating both the transformation from the input models to the target model but also the target metamodel based on the view specification. Therefore, a flaw in the ModelJoin specification also may lead (and in fact that happened) to a flaw / missing attribute in the target metamodel.

**Comment by dstrueber** [comment]
I see, makes sense. Thanks for clarifying.

**Comment by georghinkel** [comment]
Closed with commit 6ac12511e61a068bac5497a7c56037bd47833f0d
